/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/common/AppIcon.vue')['default']
    AppTooltip: typeof import('./src/components/common/AppTooltip.vue')['default']
    BiliAccountCard: typeof import('./src/components/bili/BiliAccountCard.vue')['default']
    CountdownDialog: typeof import('./src/components/dialog/countdown/CountdownDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExternalLink: typeof import('./src/components/common/ExternalLink.vue')['default']
    IconButton: typeof import('./src/components/common/IconButton.vue')['default']
    IconLabel: typeof import('./src/components/common/IconLabel.vue')['default']
    LoadingDialog: typeof import('./src/components/dialog/loading/LoadingDialog.vue')['default']
    LogPrint: typeof import('./src/components/common/LogPrint.vue')['default']
    PluginMenuItem: typeof import('./src/components/plugin/PluginMenuItem.vue')['default']
    PluginMenus: typeof import('./src/components/plugin/PluginMenus.vue')['default']
    PluginPageContent: typeof import('./src/components/plugin/PluginPageContent.vue')['default']
    PluginPageHeader: typeof import('./src/components/plugin/PluginPageHeader.vue')['default']
    SettingGroup: typeof import('./src/components/settings/SettingGroup.vue')['default']
    SettingItem: typeof import('./src/components/settings/SettingItem.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
