/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/common/AppIcon.vue')['default']
    AppTooltip: typeof import('./src/components/common/AppTooltip.vue')['default']
    BiliAccountCard: typeof import('./src/components/bili/BiliAccountCard.vue')['default']
    CountdownDialog: typeof import('./src/components/dialog/countdown/CountdownDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExternalLink: typeof import('./src/components/common/ExternalLink.vue')['default']
    IconButton: typeof import('./src/components/common/IconButton.vue')['default']
    IconLabel: typeof import('./src/components/common/IconLabel.vue')['default']
    LoadingDialog: typeof import('./src/components/dialog/loading/LoadingDialog.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
