/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/common/AppIcon.vue')['default']
    AppTooltip: typeof import('./src/components/common/AppTooltip.vue')['default']
    BiliUserCard: typeof import('./src/components/bili/BiliUserCard.vue')['default']
    CountdownDialog: typeof import('./src/components/dialog/countdown/CountdownDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExternalLink: typeof import('./src/components/common/ExternalLink.vue')['default']
    IconButton: typeof import('./src/components/common/IconButton.vue')['default']
    IconLabel: typeof import('./src/components/common/IconLabel.vue')['default']
    LoadingDialog: typeof import('./src/components/dialog/loading/LoadingDialog.vue')['default']
    LogPrint: typeof import('./src/components/common/LogPrint.vue')['default']
    PluginMenuItem: typeof import('./src/components/plugin/PluginMenuItem.vue')['default']
    PluginMenus: typeof import('./src/components/plugin/PluginMenus.vue')['default']
    PluginPageContent: typeof import('./src/components/plugin/PluginPageContent.vue')['default']
    PluginPageHeader: typeof import('./src/components/plugin/PluginPageHeader.vue')['default']
    SettingGroup: typeof import('./src/components/settings/SettingGroup.vue')['default']
    SettingItem: typeof import('./src/components/settings/SettingItem.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const AppIcon: typeof import('./src/components/common/AppIcon.vue')['default']
  const AppTooltip: typeof import('./src/components/common/AppTooltip.vue')['default']
  const BiliUserCard: typeof import('./src/components/bili/BiliUserCard.vue')['default']
  const CountdownDialog: typeof import('./src/components/dialog/countdown/CountdownDialog.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const ExternalLink: typeof import('./src/components/common/ExternalLink.vue')['default']
  const IconButton: typeof import('./src/components/common/IconButton.vue')['default']
  const IconLabel: typeof import('./src/components/common/IconLabel.vue')['default']
  const LoadingDialog: typeof import('./src/components/dialog/loading/LoadingDialog.vue')['default']
  const LogPrint: typeof import('./src/components/common/LogPrint.vue')['default']
  const PluginMenuItem: typeof import('./src/components/plugin/PluginMenuItem.vue')['default']
  const PluginMenus: typeof import('./src/components/plugin/PluginMenus.vue')['default']
  const PluginPageContent: typeof import('./src/components/plugin/PluginPageContent.vue')['default']
  const PluginPageHeader: typeof import('./src/components/plugin/PluginPageHeader.vue')['default']
  const SettingGroup: typeof import('./src/components/settings/SettingGroup.vue')['default']
  const SettingItem: typeof import('./src/components/settings/SettingItem.vue')['default']
}